## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
CUSTOM_CXX := /home/vis/.jumbo/opt/gcc48/bin/g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /home/work/cuda-5.5
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them (up to CUDA 5.5 compatible).
# For the latest architecture, you need to install CUDA >= 6.0 and uncomment
# the *_50 lines below.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		#-gencode arch=compute_50,code=sm_50 \
		#-gencode arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := mkl
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
BLAS_INCLUDE := /home/vis/yangdegang/lib/intel/mkl/include
BLAS_LIB := /home/vis/yangdegang/lib/intel/mkl/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /home/vis/.jumbo/include/python2.7/\
    /home/vis/common/lib/python2.7 \
	/home/vis/common/lib/python2.7/site-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# PYTHON_INCLUDE := $(HOME)/anaconda/include \
		# $(HOME)/anaconda/include/python2.7 \
		# $(HOME)/anaconda/lib/python2.7/site-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /home/vis/.jumbo/include/python2.7/\
	/home/vis/yangdegang/lib/local/lib

# PYTHON_LIB := $(HOME)/anaconda/lib

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) \
	/home/vis/.jumbo/include\
	/usr/include \
	/home/vis/yangdegang/lib/local/include \
	/home/vis/yangdegang/lib/local/include/opencv \
	/home/vis/yangdegang/lib/local/include/opencv2 \
	/home/vis/yangdegang/caffe/caffe_10/cudnn-6.5-linux-R1 \
	/home/work/cuda-5.5/include \
	/home/vis/yangdegang/lib/boost_1_56_0 

LIBRARY_DIRS := $(PYTHON_LIB) \
	/home/vis/.jumbo/lib\
	/usr/lib \
	/home/vis/yangdegang/lib/local/lib \
	/home/vis/yangdegang/lib/intel/lib/intel64 \
	/home/vis/yangdegang/lib/intel/mkl/lib/intel64 \
	/home/vis/yangdegang/caffe/caffe_10/cudnn-6.5-linux-R1 \
	/home/work/cuda-5.5/lib64 \
	/home/vis/yangdegang/lib/boost_1_56_0/stage/lib

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 1
